Feature/us75/patient details in dossier
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-2-Team-C pull request #77
Opened 2024-12-05 15:02 UTC by Acetoshi

fixes #75 
![image](https://github.com/user-attachments/assets/29904d4e-12ce-431d-a036-f0625c6c6f5b)
prototype : 
![image](https://github.com/user-attachments/assets/77b6a72e-bb8b-4aab-b37b-bf3ebdde1540)

- Created patient resolver and query Patient(patientId)
- Created PatientDetails component
-  Changed layout in Dossier page

2024-12-05 15:16 UTC, Adri-bis approved these changes

2024-12-05 15:25 UTC, julien44830 requested changes

2024-12-05 15:25 UTC, julien44830 commented on client/src/pages/Dossier/Dossier.tsx
> +          <p>research area placeholder</p>
sauf erreur de ma part, ce `<p>` est visible par l'utilisateur : 
` <p>research area placeholder</p>`
il faut donc le traduire en français

2024-12-05 15:25 UTC, julien44830 commented on client/src/utils/dates.utils.ts
> +  return `${age} ans`;
le patient peut-il avoir 1 an ou moins ?
`return ${age} ans`
problème mineur à mon sens mais du coup `ans` peut être `an`

2024-12-06 08:49 UTC, julien44830 approved these changes, later dismissed

2024-12-06 08:49 UTC, Adri-bis approved these changes, later dismissed

2024-12-06 11:30 UTC, julien44830 approved these changes

2024-12-06 11:31 UTC, Ektoplasme approved these changes

2024-12-06 11:32 UTC, Adri-bis approved these changes

2024-12-06 11:32 UTC, merged