Feature/admin/page
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-2-Team-C pull request #78
Opened 2024-12-05 15:06 UTC by julien44830

![Capture d'écran 2024-12-05 155959](https://github.com/user-attachments/assets/f5f83d35-7c0b-4b9b-8efd-2f9ab1465d2a)

# Création de la page admin

- création de l'objet `fakeUser` pour simuler la donnée  de l'API sur 10 `users`
- création de la fonction pour traduire les rôles via `Object.entries`
- Filtre des `users` par rôle via un `select`
- Filtre des `users` par nom via le composant searchBar
- Les boutons sont actuel relier nulle par

2024-12-05 16:18 UTC, Acetoshi commented on client/src/components/SearchBar/SearchBar.tsx
> +          aria-label="Champ de recherche d'utilisateur"
A modifier dans le futur, le aria-label doit être modifiable en props

2024-12-05 16:21 UTC, Acetoshi commented on client/src/components/UserList/Archive.svg.tsx
> +export default function Archive() {
AcrchiveIcon

2024-12-05 16:26 UTC, Acetoshi requested changes

2024-12-05 16:26 UTC, Acetoshi commented on client/src/components/SearchBar/Loupe.svg.tsx
> +export default function Loupe() {
Move all icons into an icons folder, at the same level than components

2024-12-05 16:26 UTC, Acetoshi commented on client/src/components/UserList/Modifer.svg.tsx
> +export default function Modifier() {
Modifer ? EditIcon.tsx

2024-12-05 16:26 UTC, Acetoshi commented on client/src/components/UserList/UserList.types.ts
> +interface UserProps {
Possibilité d'utiliser plutot un Pick<User, ....... > depuis codeGen, mais pas prio.

2024-12-05 16:26 UTC, Acetoshi commented on client/src/pages/Admin/fakeUsers.ts
> +import UserProps from '../../components/UserList/UserList.types.ts';
possibilité de convertir en json pour unifier les pratiques dans le futur

2024-12-05 16:32 UTC, Acetoshi commented on client/src/components/SearchBar/SearchBar.tsx
> +          aria-label="Champ de recherche d'utilisateur"
"champ de recherche"

2024-12-06 08:57 UTC, Acetoshi requested changes

2024-12-06 08:57 UTC, Acetoshi commented on client/src/components/SearchBar/SearchBar.tsx
> +          aria-label="champ de recherche"
nice !

2024-12-06 08:57 UTC, Acetoshi commented on client/src/icons/EditeIcon.tsx
> +export default function EditeIcon() {
EditeIcon > EditIcon*

2024-12-06 08:57 UTC, Acetoshi commented on client/src/icons/LoupeIcon.tsx
> +export default function LoupeIcon() {
SearchIcon*, Loupe is a french word.

2024-12-06 09:12 UTC, Acetoshi approved these changes
DOOG.

2024-12-06 09:12 UTC, Adri-bis approved these changes

2024-12-06 09:16 UTC, Ektoplasme approved these changes

2024-12-06 09:19 UTC, merged