Refacto/us83/agent page in one page
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-2-Team-C pull request #90
Opened 2024-12-11 14:51 UTC by Adri-bis

- Suppression des pages inutiles pour simplifier la navigation.

- Réorganisation du code pour regrouper toute la logique liée aux services et aux docteurs dans une seule page.

- Implémentation d'une gestion dynamique des vues avec des boutons permettant de basculer entre les services, les docteurs par service, et les docteurs généraux.

- Amélioration de la gestion des états pour assurer une transition fluide entre les différentes vues (services, docteurs par service, docteurs, patients).

2024-12-11 15:47 UTC, julien44830 requested changes

2024-12-11 15:47 UTC, julien44830 commented on client/src/components/AgentList/AgentList.tsx
> +interface AgentListProps<T> {
importer l'interface du fichier type : 
```javascript
interface AgentListProps<T> {
  isLoading: boolean;
  error?: Error | null;
  items: T[];
  emptyMessage: string;
  renderItem: (item: T) => React.ReactNode;
  onItemClick?: (item: T) => void;
}
```

2024-12-11 15:47 UTC, julien44830 commented on client/src/components/AgentList/AgentList.tsx
> +const AgentList = <T,>({
le nommage du composant reflète t'il bien ça fonction ?

`AgentList`

2024-12-11 15:47 UTC, julien44830 commented on core_api/src/modules/department/department.resolver.ts
> +    description: 'Récupère les départements par label et leurs docteurs'
cette description devrait être en anglais ?
`description: 'Récupère les départements par label et leurs docteurs'`

2024-12-11 15:47 UTC, julien44830 commented on core_api/src/modules/user/user.resolver.ts
> +    description: 'Récupère tous les utilisateurs ayant le rôle de doctor'
cette description devrait être en anglais :
`description: 'Récupère tous les utilisateurs ayant le rôle de doctor'`

2024-12-11 15:47 UTC, julien44830 commented on core_api/src/modules/user/user.resolver.ts
> +      relations: ['role', 'department', 'gender', 'workingHours'] // Ajoute les relations nécessaires
commentaire en français
`// Ajoute les relations nécessaires`

2024-12-11 15:47 UTC, julien44830 commented on core_api/src/modules/user/user.resolver.ts
> +      throw new Error("Role 'doctor' introuvable.");
gestion d'erreur en anglais ou français:
`throw new Error("Role 'doctor' introuvable.");`

2024-12-11 15:47 UTC, julien44830 commented on core_api/src/modules/department/department.resolver.ts
> +      throw new Error(`Aucun département trouvé avec le label '${label}'.`);
gestion d'erreur en anglais ou français:
` throw new Error(`Aucun département trouvé avec le label '${label}'.`);`

2024-12-11 15:47 UTC, julien44830 commented on core_api/src/modules/department/department.resolver.ts
> +      throw new Error("Role 'doctor' introuvable.");
gestion d'erreur en anglais ou français:
`throw new Error("Role 'doctor' introuvable.");`

2024-12-11 15:59 UTC, Acetoshi requested changes

2024-12-11 15:59 UTC, Acetoshi commented on client/src/components/AgentList/AgentList.tsx
> +const AgentList = <T,>({
C'est vrai qu'on s'attend à avoir une liste d'agents ici

2024-12-11 15:59 UTC, Acetoshi commented on client/src/components/AgentList/AgentList.tsx
> +const AgentList = <T,>({
Pas OK la fonction fléchée pour un composant

2024-12-11 16:17 UTC, Acetoshi commented on core_api/src/modules/user/user.resolver.ts
> +    description: 'Récupère tous les utilisateurs ayant le rôle de doctor'
pas besoin d'un resolver, faisons plutot getUsersByRole ( que julien a probablement déja codé ? )

2024-12-11 18:30 UTC, Ektoplasme approved these changes, later dismissed

2024-12-12 10:10 UTC, Acetoshi requested changes

2024-12-12 10:10 UTC, Acetoshi commented on core_api/src/modules/user/user.resolver.ts
> +export class DoctorsResolver {
a modifier en User Resolver

2024-12-12 10:10 UTC, Acetoshi commented on core_api/src/modules/department/department.resolver.ts
> +export class DoctorByDepartmentResolver {
DepartementResolver

2024-12-12 10:10 UTC, Acetoshi commented on core_api/src/modules/department/department.resolver.ts
> +  async getDoctorByDepartment(
A mettre dans le user resovler parce que la nature de ce qu'on récupère c'est User[]

2024-12-12 10:10 UTC, Acetoshi commented on client/src/components/AgentList/AgentList.tsx
> +export default function AgentList<T>({
ArgentSearchInterface ? AgentChoiceList ? Non bloquant pour moi. 
ArgentSearchChoiceList ?

2024-12-12 10:10 UTC, Acetoshi commented on client/src/pages/AgentHome/AgentHome.tsx
> +export default DynamicPage;
A mettre en haut  
export default function Dynamicpage

2024-12-12 10:10 UTC, Acetoshi commented on client/src/pages/AgentHome/AgentHome.tsx
> +    <div className="mt-8 flex flex-col items-center gap-8">{renderView()}</div>
return (
{state==='doctor' && <AllDoctors />}
{state==='patient' && <AllPatients />}
) ?

if (state==='doctor') return <AllDoctors />
if (state==='doctor') return <AllDoctors />
if (state==='doctor') return <AllDoctors />
return <IntitialAgentView />

2024-12-12 10:10 UTC, Acetoshi commented on client/src/pages/AgentHome/AgentHome.tsx
> +export default DynamicPage;
AgentHome ?

2024-12-12 10:10 UTC, Acetoshi commented on client/src/schemas/role.schema.ts
> +export const GET_DEPARTMENT_AND_DOCTOR = gql`
A déplacer

2024-12-12 10:12 UTC, teasmade commented on client/src/components/AgentList/AgentList.tsx
> +  if (error) return <p>Erreur lors du chargement : {error.message}</p>;
`error.message` - not to show for user

2024-12-12 15:02 UTC, julien44830 approved these changes

2024-12-12 18:04 UTC, teasmade approved these changes

2024-12-13 08:39 UTC, Acetoshi approved these changes
OK pour moi, ordre des imports à inverser dans la prochaine PR avec UserResolver

2024-12-13 08:39 UTC, Acetoshi commented on client/src/components/AgentList/AgentList.tsx
> +  if (error) return <p>Erreur lors du chargement : {error.message}</p>;
remplacer par  <p>Erreur lors du chargement .</p>;

2024-12-13 08:39 UTC, Acetoshi commented on client/src/components/AgentChoiceList/AgentChoiceList.tsx
> +export default function AgentChoiceList<T>({
yes :)

2024-12-13 08:39 UTC, Acetoshi commented on client/src/generated/graphql-types.ts
> +  getDoctorByDepartment: Array<Department>;
yes !

2024-12-13 08:40 UTC, merged